#!/usr/bin/env python
""" Project Euler
Problem 2
=========


   Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.

   
   Answer: 4194eb91842c8e7e6df099ca73c38f28
"""

def fib(a, b, n):
    if n >= 4e6:
        return 

def main():
  return fib(1, 1, 1)


if __name__ == "__main__":
  print(main())
