#!/usr/bin/env python
""" Project Euler
Problem 2
=========


   Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.


   Answer: 4194eb91842c8e7e6df099ca73c38f28
"""

from math import sqrt, log, floor


def main():
    s5 = sqrt(5)
    phi = (s5 + 1) / 2
    limit = 4e6
    N = floor(log((sqrt(5 * limit**2 + 4) - s5 * limit) / 2) / log(1 / phi))
    fibN = round((phi**N + phi**(-N)) / s5)
    return round((fibN * (phi + 1) - 1) / 2)


if __name__ == "__main__":
    print(main())
